### PR TITLE
update docsy and required fixes

### PR DESCRIPTION
**Pull request by splattner**

### CODE REVIEW

**Comment by splattner** [comment]
the added layouts probably need some fixing, but haven't figured it out yet
@LorenzBischof do you see it?

**Comment by LorenzBischof** [comment]
The error is caused by the following line:
https://github.com/acend/go-basics-training/blob/f0376c959f984ed50ce5f7c3ae82ac4fca49a8ba/layouts/partials/hooks/head-end.html#L3
Because the `site.css` does not exist anymore. I will have a look on the weekend and push a fix.

Probably just remove the line entirely and also the concatenation of both files at the bottom, but I currently have no time to test it.

**Comment by splattner** [comment]
thx! and no hurry, whenever you find some spare time!

**Comment by LorenzBischof** [comment]
The copy button does not appear in all code blocks. Probably because of the selector here:

https://github.com/google/docsy/blob/06a792334f9bb12bbe8eca679908ae37ee0f6228/assets/js/click-to-copy.js#L1

**Pull request merged**
